#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (C) 2012 Huayra GNU/Linux
#
# Author Luciano Abel Baraglia <luciano.baraglia@gmail.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2
# of the License
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
# USA.

from huayra_simulaciones_interactivas import SimulacionesInteractivas
from pprint import pprint
import main
import sys

sys.path.append('/usr/share/huayra-simulaciones-interactivas')

main.init()
main.sims = SimulacionesInteractivas()
main.sims.cargar_simulaciones_desde_archivo('data.simulaciones_categorias')
main.sims.iniciar()
